version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - abn
  ignore:
  - dependency-name: coverage
    versions:
    - "> 4.5.4"
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
  - dependency-name: pytest-asyncio
    versions:
    - 0.14.0
    - 0.15.0
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: tox
    versions:
    - 3.21.2
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
