repos:
- repo: https://github.com/ambv/black
  rev: 24.2.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
