language: python
dist: xenial
python:
    - 3.7
env:
  global:
    - secure: "G0SURc9kFuxcBqSOEVXzALa06VPNpZzvsxTZYeO6UpSuuxqCSebk9q1PJUj8u9i6hmoEDQgwftxTCxjuMwMMNd2wFnRceOaD2kmHCCVoYY0Z+x630Is1OwvmIb39sWLFl64XTUfU3M8uQxuk6Pid4WhK8U7aDwLzteEVaDGhKOKODDkUMIZRrMfgINSxJag/k+jyAIq06u3MWkfc3DT76k16ZiKXZNy/EX+IsBli46PGFoCZMhzIBuQ6ym7IkZc6CAlputtbWtACmUaqUy8M+sZp7TYoZ8kQnGh8Y/jhzVPVrz+5bQuhOlSzh8kSpjYGP3O+ePKHzgnovihWpe5MlVCPJbTeSihY4d7ExiouUIJzef5i83Jtxuvl6GB/CWMkNP+RePB6rC0mf8ExsVa4OHM3hFRrWcs/YSyDfQy4pX0Wng0has7cV2SiGcBUibJBKvcmWDpLfJiX73xL6rzfYDk4M5DlaX0yo6H3PXFfWkSjFOI7pFkYwRXM3NzOwcwM9J7FMmf1Sx2mHFUTm4rtnfzC/cMMO1hbV0R9UNS0JydoG2LGi+JVrzjTG8OD6UtvKu8peQbgcN02e7Cm9EYmJrTJ38n2gOkevg2E7WjtAMO/+iRRPqmz+qY2oq/Cj876O7ncshFbiZmJFllcNPjdGb7Kt0MCK4oVH/hYK+6oS6I="

install:
  - pip install poetry
  - poetry add --dev appdirs
  - poetry install

script: ignore

jobs:
  include:
    - stage: build
      python: 3.7
      script:
        - poetry build
      if: tag IS NOT present
    - stage: deploy
      python: 3.7
      script:
        - poetry config http-basic.pypi "__token__" "${PYPI_API_TOKEN}"
        - poetry publish --build
      if: tag IS present
