name: Publish Release

on:
  push:
    tags:
      - v**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Setup release environment
      run: pipx install poetry
    - name: Configure pypi credentials
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry config http-basic.pypi __token__ "$PYPI_API_TOKEN"
    - name: Build and publish package to PyPI
      run: poetry publish --build
